### ISSUE TITLE
正常来说预览图的路径是什么啊，我试着自己加进去试试能不能看到，还是说计划什么时候添加呢

### ISSUE THREAD

**Issue by users3524** [5Jbgr/carolineModCtrl#10]

**Comment by 5Jbgr** [comment]
选中模组然后将图片拖放到预览图那一栏，或者右键从剪切板粘贴 @users3524

**Comment by 5Jbgr** [comment]
预览图位于软件所在位置的image目录中

**Comment by users3524** [comment]
![PixPin_2024-08-23_17-39-31](https://github.com/user-attachments/assets/5f8bd447-3ee6-4415-a831-87793944761f)，拖进去发生报错了

**Comment by users3524** [comment]
> 预览图位于软件所在位置的image目录中

拖进去发生报错了

**Comment by users3524** [comment]
> 选中模组然后将图片拖放到预览图那一栏，或者右键从剪切板粘贴 @users3524

拖进去发生报错了，复制提示剪切板为空

**Comment by 5Jbgr** [comment]
从剪切板读取图片不能从文件管理器中复制图片文件，一般需要打开图片复制，或者通过截图的方式复制，或者是网页中右键复制图片选项得到的结果，简单来说可以通过系统剪切板看到图片说明能够读取。通过按win+v键可查看系统剪切板

**Comment by 5Jbgr** [comment]
已修复 @users3524
