### ISSUE TITLE
官服目录下并没有data文件

### ISSUE THREAD

**Issue by Wmangen** [5Jbgr/carolineModCtrl#12]

**Comment by 5Jbgr** [comment]
官服是对应启动器所在的目录

**Comment by 5Jbgr** [comment]
之前确实没有见到过这种目录结构，我想想怎么解决

**Comment by 5Jbgr** [comment]
在[v0.4.3](https://github.com/5Jbgr/carolineModCtrl/releases/tag/v0.4.3)中添加的新版启动器对应的目录结构，可以尝试一下看看有没有错误
@Wmangen
