### ISSUE TITLE
I can't find the exe

### ISSUE THREAD

**Issue by yuxin6931246** [5Jbgr/carolineModCtrl#13]
there is no exe in this package, how can we run it up?

**Comment by 5Jbgr** [comment]
You can find the releases option on the right end of the webpage, where you can find the zip file with executable files

https://github.com/5Jbgr/carolineModCtrl/releases/tag/v0.4.2
@yuxin6931246

**Comment by yuxin6931246** [comment]
> You can find the releases option on the right end of the webpage, where you can find the zip file with executable files
> 
> https://github.com/5Jbgr/carolineModCtrl/releases/tag/v0.4.2 @yuxin6931246

TKS
