### ISSUE TITLE
错误代码

### ISSUE THREAD

**Issue by HengBei99** [5Jbgr/carolineModCtrl#21]
![4acc2b4e-87fb-41c9-a486-1d3c5327276d](https://github.com/user-attachments/assets/f86ba640-ae59-4caf-affb-5660f2b800cd)

**Comment by HengBei99** [comment]
一直报错打不开

**Comment by HengBei99** [comment]
这咋整

**Comment by 5Jbgr** [comment]
已修复，下载fix版本即可 @HengBei99

**Comment by HengBei99** [comment]
效率真快，nb
