### ISSUE TITLE
请问下导入成功以后再游戏内没效果是怎么解决呢？

### ISSUE THREAD

**Issue by Marvin-Gao** [5Jbgr/carolineModCtrl#5]
SNOWBREAK\data\game\Game\Content\Paks\~mod
确认导入到这个目录下面了 谢谢！

**Comment by Marvin-Gao** [comment]
破案了。 steam版的目录有问题，应该是STEAM\steamapps\common\SNOWBREAK\Game\Content\Paks 老哥能update一下吗 谢谢

**Comment by 5Jbgr** [comment]
> 破案了。 steam版的目录有问题，应该是STEAM\steamapps\common\SNOWBREAK\Game\Content\Paks 老哥能update一下吗 谢谢

@Marvin-Gao  已尝试在[v0.3.7](https://github.com/5Jbgr/carolineModCtrl/releases/tag/v0.3.7)中修复此问题

**Comment by Marvin-Gao** [comment]
谢谢老哥

**Comment by 5Jbgr** [comment]
不客气
