### ISSUE TITLE
新版本支持

### ISSUE THREAD

**Issue by W0910** [5Jbgr/carolineModCtrl#7]
大佬还维护项目吗？希望更新周年庆版本的时装

**Comment by 5Jbgr** [comment]
正在被论文折磨，搞完会更新的，新时装的适配在最新[release](https://github.com/5Jbgr/carolineModCtrl/releases/tag/v0.3.7)里的[category.zip](https://github.com/5Jbgr/carolineModCtrl/releases/download/v0.3.7/category.zip)，对照版本说明即可。 @W0910

**Comment by W0910** [comment]
更新成功，感谢大佬
