### ISSUE TITLE
更新软件后遇到的报错

### ISSUE THREAD

**Issue by W0910** [5Jbgr/carolineModCtrl#9]
大佬，今天下了新软件添加mod时遇到的报错，请问怎么处理
![屏幕截图 2024-08-23 111210](https://github.com/user-attachments/assets/96a60e1a-03fc-488a-92bf-d94097956ebe)

**Comment by W0910** [comment]
弹窗以后【添加】键变灰色点不动了

**Comment by 5Jbgr** [comment]
正在修复 @W0910

**Comment by 5Jbgr** [comment]
已在[新版本](https://github.com/5Jbgr/carolineModCtrl/releases/tag/v0.4.1)修复 @W0910

**Comment by W0910** [comment]
问题已解决，新版软件运行成功，感谢更新与维护。by the way, 以后能不能出一个老版本数据导入新版本功能，一个一个重新装载mod还是太噩梦了
![屏幕截图(509)](https://github.com/user-attachments/assets/72730738-0fb8-4fe4-b46e-7fcf0d0f9ba0)

**Comment by 5Jbgr** [comment]
只要不删除软件所在目录的modinfo.db，所有记录都会保存，更新软件时基本覆盖原文件就可以了，通常不需要全部删除 @W0910

**Comment by 5Jbgr** [comment]
可否将报错内容贴出？ @Wmangen

**Comment by MegaMawile303** [comment]
![QQ截图20240825183611](https://github.com/user-attachments/assets/1e474896-c012-4724-914d-1c23460e8ae6)

**Comment by 5Jbgr** [comment]
问题已经在[v0.4.3](https://github.com/5Jbgr/carolineModCtrl/releases/tag/v0.4.3)中尝试解决
@MegaMawile303
